#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt35512_dsi_vdo_wvga_zhongguangdian_shenchao.o



ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

